"""Seed catalog for Keneth Global — Masalas + Home Decor Cloth."""
from datetime import datetime, timezone

# All prices are EUR (Europe market). Weights indicate grams / dimensions.
# image_prompt is used by Gemini Nano Banana to generate a hero product shot.

CATALOG = [
    # ---------- MASALAS (Indian Spices) ----------
    {
        "slug": "royal-garam-masala",
        "name": {
            "en": "Royal Garam Masala",
            "de": "Königliches Garam Masala",
            "fr": "Garam Masala Royal",
            "es": "Garam Masala Real",
            "it": "Garam Masala Reale",
        },
        "vertical": "masalas",
        "category": "blended-spices",
        "price_eur": 8.90,
        "unit": "100g",
        "short_description": {
            "en": "A regal blend of 12 hand-roasted spices — the soul of North Indian cuisine.",
            "de": "Eine königliche Mischung aus 12 handgerösteten Gewürzen — die Seele der nordindischen Küche.",
            "fr": "Un mélange royal de 12 épices torréfiées à la main — l'âme de la cuisine du nord de l'Inde.",
            "es": "Una mezcla real de 12 especias tostadas a mano — el alma de la cocina del norte de India.",
            "it": "Una miscela regale di 12 spezie tostate a mano — l'anima della cucina del nord dell'India.",
        },
        "long_description": {
            "en": "Cardamom, clove, black pepper, cinnamon, cumin and mace slow-toasted over open flame and stone-ground the same afternoon. Small batches, sealed within hours of milling.",
            "de": "Kardamom, Nelke, schwarzer Pfeffer, Zimt, Kreuzkümmel und Muskatblüte über offener Flamme geröstet und noch am selben Nachmittag steingemahlen.",
            "fr": "Cardamome, girofle, poivre noir, cannelle, cumin et macis torréfiés à la flamme et broyés à la pierre le même après-midi.",
            "es": "Cardamomo, clavo, pimienta negra, canela, comino y macis tostados a fuego abierto y molidos en piedra la misma tarde.",
            "it": "Cardamomo, chiodi di garofano, pepe nero, cannella, cumino e macis tostati a fiamma viva e macinati a pietra lo stesso pomeriggio.",
        },
        "image_prompt": "Editorial luxury food photography of Indian Garam Masala spice blend, deep amber colored ground spice piled on a dark slate stone with whole cardamom pods, cinnamon sticks and black peppercorns scattered around, dramatic side lighting, moody chiaroscuro, warm brass tones, magazine cover quality, ultra sharp macro detail, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&q=80",
        "badge": {"en": "Bestseller", "de": "Bestseller", "fr": "Meilleure vente", "es": "Más vendido", "it": "Best seller"},
    },
    {
        "slug": "kashmiri-red-chilli",
        "name": {
            "en": "Kashmiri Red Chilli Powder",
            "de": "Kaschmirisches Chilipulver",
            "fr": "Piment Rouge du Cachemire",
            "es": "Chile Rojo de Cachemira",
            "it": "Peperoncino Rosso del Kashmir",
        },
        "vertical": "masalas",
        "category": "single-spices",
        "price_eur": 6.50,
        "unit": "100g",
        "short_description": {
            "en": "Deep ruby colour, gentle warmth. The chef's choice for luminous curries.",
            "de": "Tiefes Rubinrot, sanfte Schärfe. Die Wahl des Chefs für leuchtende Currys.",
            "fr": "Couleur rubis profond, chaleur douce. Le choix du chef pour des currys lumineux.",
            "es": "Color rubí profundo, calidez suave. La elección del chef para curries luminosos.",
            "it": "Colore rosso rubino, calore delicato. La scelta dello chef per curry luminosi.",
        },
        "long_description": {
            "en": "Sun-dried Kashmiri chillies renowned for their vivid crimson pigment and mild pungency. Adds colour without overwhelming heat.",
            "de": "Sonnengetrocknete Kaschmiri-Chilis, bekannt für ihre leuchtend rote Farbe und milde Schärfe.",
            "fr": "Piments du Cachemire séchés au soleil, réputés pour leur pigment cramoisi et leur douceur.",
            "es": "Chiles de Cachemira secados al sol, famosos por su color carmesí y suave picor.",
            "it": "Peperoncini del Kashmir essiccati al sole, celebri per il loro pigmento cremisi e la loro dolcezza.",
        },
        "image_prompt": "Editorial macro photography of Kashmiri red chilli powder, vibrant crimson red ground spice heaped on dark textured slate, with a few whole dried chillies beside it, dramatic warm light from left, deep shadows, magazine luxury food photography, ultra high resolution, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1701166642770-cdcf6d5e0801?w=1200&q=80",
    },
    {
        "slug": "turmeric-gold",
        "name": {
            "en": "Turmeric Gold — Alleppey Finger",
            "de": "Kurkuma Gold — Alleppey Finger",
            "fr": "Curcuma d'Or — Alleppey Finger",
            "es": "Cúrcuma Dorada — Alleppey Finger",
            "it": "Curcuma d'Oro — Alleppey Finger",
        },
        "vertical": "masalas",
        "category": "single-spices",
        "price_eur": 7.20,
        "unit": "150g",
        "short_description": {
            "en": "High-curcumin single-origin turmeric from Kerala's Alleppey coast.",
            "de": "Hochkurkuminhaltiges Kurkuma aus der Alleppey-Küste Keralas.",
            "fr": "Curcuma monovariétal à haute teneur en curcumine de la côte d'Alleppey au Kerala.",
            "es": "Cúrcuma de origen único con alto contenido de curcumina de la costa de Alleppey en Kerala.",
            "it": "Curcuma monovarietale ad alto contenuto di curcumina dalla costa di Alleppey nel Kerala.",
        },
        "long_description": {
            "en": "Prized for its 5% curcumin content and rich saffron-yellow hue. Traditionally used in golden milk, curries and holistic wellness rituals.",
            "de": "Geschätzt für seinen 5% Curcumin-Gehalt und den reichen safranrgelben Farbton.",
            "fr": "Apprécié pour sa teneur de 5% en curcumine et sa teinte jaune safran.",
            "es": "Apreciada por su contenido de 5% de curcumina y su tono amarillo azafrán.",
            "it": "Apprezzata per il suo contenuto del 5% di curcumina e la sua tonalità giallo zafferano.",
        },
        "image_prompt": "Editorial macro photograph of golden turmeric powder, vibrant saffron yellow spice mounded on a dark slate surface with fresh turmeric root beside it, dramatic side lighting creating warm glow, deep black background, luxury food magazine aesthetic, ultra sharp detail",
        "image_hint": "https://images.unsplash.com/photo-1615485500704-8e990f9f5be4?w=1200&q=80",
    },
    {
        "slug": "cardamom-green-pods",
        "name": {
            "en": "Green Cardamom — Malabar Grade AAA",
            "de": "Grüner Kardamom — Malabar AAA",
            "fr": "Cardamome Verte — Malabar AAA",
            "es": "Cardamomo Verde — Malabar AAA",
            "it": "Cardamomo Verde — Malabar AAA",
        },
        "vertical": "masalas",
        "category": "whole-spices",
        "price_eur": 14.90,
        "unit": "50g",
        "short_description": {
            "en": "Plump, aromatic pods hand-picked from the misty Malabar hills.",
            "de": "Pralle, aromatische Schoten, von Hand aus den nebligen Malabar-Hügeln gepflückt.",
            "fr": "Gousses charnues et aromatiques, cueillies à la main dans les collines brumeuses du Malabar.",
            "es": "Vainas carnosas y aromáticas, recogidas a mano en las brumosas colinas de Malabar.",
            "it": "Baccelli carnosi e aromatici, raccolti a mano dalle nebbiose colline del Malabar.",
        },
        "long_description": {
            "en": "The 'Queen of Spices'. Delicate green pods with pronounced camphor-eucalyptus aroma — used across sweet and savoury dishes and elegant chai.",
            "de": "Die 'Königin der Gewürze'. Zarte grüne Schoten mit ausgeprägtem Kampfer-Eukalyptus-Aroma.",
            "fr": "La 'Reine des Épices'. Gousses vertes délicates au parfum prononcé de camphre et d'eucalyptus.",
            "es": "La 'Reina de las Especias'. Vainas verdes delicadas con pronunciado aroma a alcanfor y eucalipto.",
            "it": "La 'Regina delle Spezie'. Baccelli verdi delicati dal pronunciato aroma di canfora ed eucalipto.",
        },
        "image_prompt": "Editorial luxury photography of premium green cardamom pods, vibrant green whole cardamom scattered on a dark slate stone, some pods split open showing dark seeds, dramatic side light, deep black background with warm glow, ultra sharp macro detail, cinematic magazine quality",
        "image_hint": "https://images.unsplash.com/photo-1701166642770-cdcf6d5e0801?w=1200&q=80",
        "badge": {"en": "Premium", "de": "Premium", "fr": "Premium", "es": "Premium", "it": "Premium"},
    },
    {
        "slug": "biryani-masala",
        "name": {
            "en": "Nawabi Biryani Masala",
            "de": "Nawabi Biryani Gewürz",
            "fr": "Épices Biryani Nawabi",
            "es": "Especias Biryani Nawabi",
            "it": "Spezie Biryani Nawabi",
        },
        "vertical": "masalas",
        "category": "blended-spices",
        "price_eur": 9.50,
        "unit": "100g",
        "short_description": {
            "en": "The royal blend for saffron-scented biryani — 18 ingredients, seven-hour slow toast.",
            "de": "Die königliche Mischung für safranduftendes Biryani — 18 Zutaten, siebenstündige Röstung.",
            "fr": "Le mélange royal pour biryani au safran — 18 ingrédients, torréfaction lente de sept heures.",
            "es": "La mezcla real para biryani con azafrán — 18 ingredientes, tostado lento de siete horas.",
            "it": "La miscela reale per biryani allo zafferano — 18 ingredienti, tostatura lenta di sette ore.",
        },
        "long_description": {
            "en": "Inspired by the imperial kitchens of Lucknow. Star anise, black stone flower, dried rose petals and mace layered with warming spices.",
            "de": "Inspiriert von den kaiserlichen Küchen von Lucknow. Sternanis, Steinblume, Rosenblätter und Muskatblüte.",
            "fr": "Inspiré des cuisines impériales de Lucknow. Anis étoilé, fleur de pierre, pétales de rose et macis.",
            "es": "Inspirado en las cocinas imperiales de Lucknow. Anís estrellado, flor de piedra, pétalos de rosa y macis.",
            "it": "Ispirato alle cucine imperiali di Lucknow. Anice stellato, fiore di pietra, petali di rosa e macis.",
        },
        "image_prompt": "Editorial luxury food photography of Indian biryani masala spice blend, warm reddish-brown ground spice on dark slate with whole star anise, cinnamon sticks, dried rose petals and bay leaves scattered around, dramatic warm golden lighting, deep shadows, magazine quality macro detail",
        "image_hint": "https://images.unsplash.com/photo-1583431298864-be18abee9de6?w=1200&q=80",
    },
    {
        "slug": "chai-masala",
        "name": {
            "en": "Signature Chai Masala",
            "de": "Signature Chai Masala",
            "fr": "Chai Masala Signature",
            "es": "Chai Masala Signature",
            "it": "Chai Masala Signature",
        },
        "vertical": "masalas",
        "category": "blended-spices",
        "price_eur": 5.90,
        "unit": "80g",
        "short_description": {
            "en": "Ginger, cardamom, black pepper and clove — a spoonful transforms your tea.",
            "de": "Ingwer, Kardamom, schwarzer Pfeffer und Nelke — ein Löffel verwandelt Ihren Tee.",
            "fr": "Gingembre, cardamome, poivre noir et girofle — une cuillère transforme votre thé.",
            "es": "Jengibre, cardamomo, pimienta negra y clavo — una cucharada transforma tu té.",
            "it": "Zenzero, cardamomo, pepe nero e chiodi di garofano — un cucchiaio trasforma il tuo tè.",
        },
        "long_description": {
            "en": "The house chai blend — balanced, warming, sweetly aromatic. Perfect for milk tea, oat lattes and winter mornings.",
            "de": "Die Haus-Chai-Mischung — ausgewogen, wärmend, süßlich aromatisch.",
            "fr": "Le mélange chai maison — équilibré, réchauffant, doucement aromatique.",
            "es": "La mezcla de chai de la casa — equilibrada, cálida, dulcemente aromática.",
            "it": "La miscela chai della casa — equilibrata, calda, dolcemente aromatica.",
        },
        "image_prompt": "Editorial luxury photography of masala chai spice blend, warm brown ground spice piled on dark slate with whole cinnamon sticks, star anise, cardamom pods, cloves and fresh ginger slices arranged around, steam rising, dramatic warm side lighting, magazine cover quality",
        "image_hint": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=1200&q=80",
    },
    # ---------- HOME DECOR CLOTH ----------
    {
        "slug": "mughal-garden-bedsheet-king",
        "name": {
            "en": "Mughal Garden Bedsheet — King",
            "de": "Mogulgarten Bettlaken — King",
            "fr": "Drap Jardin Moghol — King",
            "es": "Sábana Jardín Mogol — King",
            "it": "Lenzuolo Giardino Moghul — King",
        },
        "vertical": "home-furnishing",
        "category": "bedsheets",
        "price_eur": 89.00,
        "unit": "270 × 275 cm",
        "short_description": {
            "en": "300-thread cotton with hand-block Mughal florals in ink and amber.",
            "de": "300-Faden-Baumwolle mit handgedruckten Mogul-Blumenmustern in Tinte und Bernstein.",
            "fr": "Coton 300 fils avec fleurs mogholes imprimées à la main en encre et ambre.",
            "es": "Algodón 300 hilos con florales mogol estampados a mano en tinta y ámbar.",
            "it": "Cotone 300 fili con fiori Moghul stampati a mano in inchiostro e ambra.",
        },
        "long_description": {
            "en": "Long-staple cotton woven in Panipat, printed by three generations of block-print artisans in Sanganer. Includes fitted sheet + two pillowcases.",
            "de": "Langstapel-Baumwolle aus Panipat, bedruckt von drei Generationen Blockdruck-Handwerkern in Sanganer.",
            "fr": "Coton à fibres longues tissé à Panipat, imprimé par trois générations d'artisans à Sanganer.",
            "es": "Algodón de fibra larga tejido en Panipat, estampado por tres generaciones de artesanos en Sanganer.",
            "it": "Cotone a fibra lunga tessuto a Panipat, stampato da tre generazioni di artigiani a Sanganer.",
        },
        "image_prompt": "Editorial luxury interior photography of a king-size bedsheet with intricate Mughal floral block-print pattern in deep indigo ink and warm amber gold on cream cotton, dramatically draped on a dark carved wooden bed, moody warm bedroom lighting from a single window, deep shadows, magazine cover quality, ultra sharp detail, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80",
        "badge": {"en": "Handcrafted", "de": "Handgefertigt", "fr": "Fait main", "es": "Hecho a mano", "it": "Fatto a mano"},
    },
    {
        "slug": "brass-cushion-cover-set",
        "name": {
            "en": "Brass Weave Cushion Cover — Set of 2",
            "de": "Messing-Kissenbezug — 2er-Set",
            "fr": "Housse Coussin Laiton — Lot de 2",
            "es": "Funda Cojín Latón — Set de 2",
            "it": "Federa Cuscino Ottone — Set da 2",
        },
        "vertical": "home-furnishing",
        "category": "cushion-covers",
        "price_eur": 42.00,
        "unit": "45 × 45 cm",
        "short_description": {
            "en": "Silk-cotton blend with metallic brass thread embroidery in geometric jaali.",
            "de": "Seiden-Baumwoll-Mischung mit metallischer Messingfaden-Stickerei in geometrischem Jaali.",
            "fr": "Mélange soie-coton avec broderie de fil de laiton métallique en jaali géométrique.",
            "es": "Mezcla seda-algodón con bordado de hilo de latón metálico en jaali geométrico.",
            "it": "Misto seta-cotone con ricamo in filo di ottone metallico in jaali geometrico.",
        },
        "long_description": {
            "en": "Inspired by carved jaali screens of Rajput palaces. Zipper closure, hidden invisible finish. Pillow insert sold separately.",
            "de": "Inspiriert von geschnitzten Jaali-Schirmen der Rajput-Paläste. Reißverschluss, unsichtbarer Verschluss.",
            "fr": "Inspiré des écrans jaali sculptés des palais Rajput. Fermeture éclair, finition invisible.",
            "es": "Inspirado en las pantallas jaali talladas de los palacios Rajput. Cierre de cremallera, acabado invisible.",
            "it": "Ispirato agli schermi jaali intagliati dei palazzi Rajput. Chiusura a cerniera, finitura invisibile.",
        },
        "image_prompt": "Editorial luxury photography of two square cushion covers in deep charcoal silk-cotton with intricate brass gold thread embroidery in geometric jaali lattice pattern, styled on a dark tufted velvet sofa, dramatic warm side lighting, deep shadows, ultra sharp detail, magazine interior design quality, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=1200&q=80",
    },
    {
        "slug": "banarasi-table-runner",
        "name": {
            "en": "Banarasi Silk Table Runner",
            "de": "Banarasi-Seiden-Tischläufer",
            "fr": "Chemin de Table en Soie Banarasi",
            "es": "Camino de Mesa Seda Banarasi",
            "it": "Runner da Tavola in Seta Banarasi",
        },
        "vertical": "home-furnishing",
        "category": "table-runners",
        "price_eur": 68.00,
        "unit": "40 × 220 cm",
        "short_description": {
            "en": "Woven Banarasi silk with real zari borders — dinner-party heirloom.",
            "de": "Gewebte Banarasi-Seide mit echten Zari-Bordüren — Erbstück für Dinnerpartys.",
            "fr": "Soie Banarasi tissée avec bordures en zari véritable — héritage de dîner.",
            "es": "Seda Banarasi tejida con bordes de zari auténtico — reliquia de cena.",
            "it": "Seta Banarasi tessuta con bordi in zari autentico — cimelio da cena.",
        },
        "long_description": {
            "en": "Hand-loomed in Varanasi by fifth-generation weavers. Deep emerald body with 24k-gilded silver zari borders. Dry clean only.",
            "de": "Handgewebt in Varanasi von Webern der fünften Generation. Tiefes Smaragdgrün mit 24k vergoldeten Silber-Zari-Rändern.",
            "fr": "Tissé à la main à Varanasi par des tisserands de cinquième génération. Corps émeraude profond avec bordures en zari argenté doré à l'or 24k.",
            "es": "Tejido a mano en Varanasi por tejedores de quinta generación. Cuerpo esmeralda profundo con bordes de zari plateado dorado 24k.",
            "it": "Tessuto a mano a Varanasi da tessitori di quinta generazione. Corpo verde smeraldo profondo con bordi in zari argento dorato 24k.",
        },
        "image_prompt": "Editorial luxury tabletop photography of a long silk table runner in deep emerald green with intricate gold zari border embroidery, elegantly draped down a dark walnut dining table with brass candlesticks and crystal glasses, moody warm candlelight, deep shadows, ultra sharp detail, magazine interior cover quality, cinematic",
        "image_hint": "https://images.pexels.com/photos/6803946/pexels-photo-6803946.jpeg?w=1200&q=80",
        "badge": {"en": "Limited", "de": "Limitiert", "fr": "Édition limitée", "es": "Edición limitada", "it": "Edizione limitata"},
    },
    {
        "slug": "kashmiri-wall-hanging",
        "name": {
            "en": "Kashmiri Chinar Wall Hanging",
            "de": "Kaschmirisches Chinar Wandbehang",
            "fr": "Tenture Murale Chinar du Cachemire",
            "es": "Tapiz Chinar de Cachemira",
            "it": "Arazzo Chinar del Kashmir",
        },
        "vertical": "home-furnishing",
        "category": "wall-hangings",
        "price_eur": 210.00,
        "unit": "90 × 150 cm",
        "short_description": {
            "en": "Hand-embroidered crewel wool tapestry of chinar leaves in autumn tones.",
            "de": "Handbestickter Crewel-Woll-Wandteppich mit Chinar-Blättern in Herbsttönen.",
            "fr": "Tapisserie en laine crewel brodée à la main aux feuilles de chinar en tons d'automne.",
            "es": "Tapiz de lana crewel bordado a mano con hojas de chinar en tonos de otoño.",
            "it": "Arazzo in lana crewel ricamato a mano con foglie di chinar in toni autunnali.",
        },
        "long_description": {
            "en": "Sourced directly from Srinagar workshops. Each piece takes six weeks to complete. Includes wooden rod and hanging cord.",
            "de": "Direkt aus den Werkstätten von Srinagar. Jedes Stück braucht sechs Wochen. Inklusive Holzstab und Aufhängeschnur.",
            "fr": "Directement des ateliers de Srinagar. Chaque pièce prend six semaines. Tige en bois et cordon inclus.",
            "es": "Directamente de los talleres de Srinagar. Cada pieza toma seis semanas. Incluye barra de madera y cordón.",
            "it": "Direttamente dai laboratori di Srinagar. Ogni pezzo richiede sei settimane. Include asta di legno e cordone.",
        },
        "image_prompt": "Editorial luxury interior photography of a hand-embroidered Kashmiri wool wall hanging tapestry featuring intricate autumn chinar maple leaves in rust, gold and deep burgundy on cream background, hung on a dark textured plaster wall with warm gallery lighting from above, deep shadows, ultra sharp detail, magazine cover quality, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1721206625305-6ce6ecc2c65f?w=1200&q=80",
    },
    {
        "slug": "pillow-cover-jaipur",
        "name": {
            "en": "Jaipur Bloom Pillow Cover Pair",
            "de": "Jaipur Bloom Kissenbezug-Paar",
            "fr": "Housse de Coussin Jaipur — Paire",
            "es": "Funda Almohada Jaipur — Par",
            "it": "Federa Jaipur — Coppia",
        },
        "vertical": "home-furnishing",
        "category": "pillow-covers",
        "price_eur": 38.00,
        "unit": "50 × 76 cm",
        "short_description": {
            "en": "Sanganer block-printed cotton pillow covers in botanical damask.",
            "de": "Sanganer blockgedruckte Baumwoll-Kissenbezüge in botanischem Damast.",
            "fr": "Housses de coussin en coton imprimées à Sanganer en damas botanique.",
            "es": "Fundas de almohada en algodón estampadas en Sanganer en damasco botánico.",
            "it": "Federe in cotone stampate a Sanganer in damasco botanico.",
        },
        "long_description": {
            "en": "Pure cotton, 200-thread. Natural indigo and madder-root dyes. Envelope closure for easy laundering. Set of 2.",
            "de": "Reine Baumwolle, 200-Faden. Natürliche Indigo- und Krappwurzelfarben. Umschlag-Verschluss.",
            "fr": "Coton pur, 200 fils. Teintures naturelles à l'indigo et à la garance. Fermeture enveloppe.",
            "es": "Algodón puro, 200 hilos. Tintes naturales de índigo y raíz de rubia. Cierre sobre.",
            "it": "Cotone puro, 200 fili. Tinture naturali all'indaco e alla robbia. Chiusura a busta.",
        },
        "image_prompt": "Editorial luxury bedroom photography of two rectangular pillow covers with intricate Jaipur block-print botanical damask pattern in deep indigo blue and warm amber on natural cream cotton, styled on a dark linen bed with brass side lamp, moody warm bedroom lighting, deep shadows, ultra sharp detail, magazine quality",
        "image_hint": "https://images.pexels.com/photos/6480707/pexels-photo-6480707.jpeg?w=1200&q=80",
    },
    {
        "slug": "silk-dining-sheet",
        "name": {
            "en": "Marigold Silk Dining Sheet",
            "de": "Ringelblumen-Seiden-Tischdecke",
            "fr": "Nappe en Soie Marigold",
            "es": "Mantel de Seda Marigold",
            "it": "Tovaglia in Seta Marigold",
        },
        "vertical": "home-furnishing",
        "category": "dining-sheets",
        "price_eur": 145.00,
        "unit": "180 × 300 cm",
        "short_description": {
            "en": "Raw silk tablecloth in marigold saffron — a festive centrepiece for eight.",
            "de": "Rohseiden-Tischtuch in Ringelblumen-Safran — festliches Herzstück für acht.",
            "fr": "Nappe en soie brute couleur safran de souci — pièce maîtresse festive pour huit.",
            "es": "Mantel de seda cruda en azafrán marigold — pieza central festiva para ocho.",
            "it": "Tovaglia in seta grezza color zafferano — pezzo centrale festivo per otto.",
        },
        "long_description": {
            "en": "Woven from raw dupion silk with a naturally textured slub finish. Hand-hemmed edges with delicate zari trim.",
            "de": "Gewebt aus Rohdupion-Seide mit natürlich strukturierter Slub-Ausführung. Handgesäumte Kanten.",
            "fr": "Tissé en soie dupion brute avec finition slub texturée. Ourlets faits main avec finition zari délicate.",
            "es": "Tejido en seda dupion cruda con acabado slub texturizado. Dobladillos hechos a mano con ribete zari.",
            "it": "Tessuto in seta dupion grezza con finitura slub testurizzata. Orli fatti a mano con rifinitura zari.",
        },
        "image_prompt": "Editorial luxury tabletop photography of a long silk tablecloth in vibrant marigold saffron orange draped over a formal dining table set with brass plates, crystal wine glasses and candles, dramatic warm candlelight, deep shadows, magazine cover quality interior design shoot, ultra sharp detail",
        "image_hint": "https://images.pexels.com/photos/6803946/pexels-photo-6803946.jpeg?w=1200&q=80",
    },
    # ---------- ARTIFICIAL JEWELRY ----------
    {
        "slug": "kundan-choker-set",
        "name": {
            "en": "Kundan Royal Choker Set",
            "de": "Kundan Königliches Choker-Set",
            "fr": "Parure Ras-du-Cou Kundan Royal",
            "es": "Conjunto Gargantilla Kundan Real",
            "it": "Parure Girocollo Kundan Reale",
        },
        "vertical": "artificial-jewelry",
        "category": "necklaces",
        "price_eur": 78.00,
        "unit": "Choker + earrings",
        "short_description": {
            "en": "Uncut-glass kundan choker with pearl drops — instant heirloom for red-carpet nights.",
            "de": "Ungeschliffener Kundan-Choker mit Perlentropfen — sofortiges Erbstück für glamouröse Abende.",
            "fr": "Ras-du-cou kundan en verre non taillé avec gouttes de perles — héritage instantané.",
            "es": "Gargantilla kundan de vidrio sin tallar con perlas — reliquia instantánea.",
            "it": "Girocollo kundan in vetro non tagliato con gocce di perle — cimelio istantaneo.",
        },
        "long_description": {
            "en": "Handset kundan stones in 22k-gold-plated brass, finished with fresh-water pearl drops and a hand-braided silk dori. Nickel-free, hypoallergenic. Comes in a velvet gift box.",
            "de": "Handgesetzte Kundan-Steine in 22k-vergoldetem Messing, veredelt mit Süßwasserperlen-Tropfen und geflochtener Seidenschnur.",
            "fr": "Pierres kundan serties main sur laiton plaqué or 22k, finies par des gouttes de perles d'eau douce.",
            "es": "Piedras kundan engastadas a mano en latón chapado en oro 22k, con gotas de perlas de agua dulce.",
            "it": "Pietre kundan incastonate a mano su ottone placcato oro 22k, con gocce di perle d'acqua dolce.",
        },
        "image_prompt": "Editorial luxury jewelry photography of an Indian kundan choker necklace with matching earrings, uncut white glass stones set in 22k gold with fresh water pearl drops, displayed on rich deep burgundy velvet, dramatic warm side lighting creating soft glow on gold, deep black shadows, ultra sharp macro detail, magazine cover quality Vogue India aesthetic, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=1200&q=80",
        "badge": {"en": "Bestseller", "de": "Bestseller", "fr": "Meilleure vente", "es": "Más vendido", "it": "Best seller"},
    },
    {
        "slug": "polki-jhumka-earrings",
        "name": {
            "en": "Polki Jhumka Earrings",
            "de": "Polki Jhumka Ohrringe",
            "fr": "Boucles d'Oreilles Polki Jhumka",
            "es": "Pendientes Polki Jhumka",
            "it": "Orecchini Polki Jhumka",
        },
        "vertical": "artificial-jewelry",
        "category": "earrings",
        "price_eur": 42.00,
        "unit": "Pair",
        "short_description": {
            "en": "Bell-shaped chandelier earrings in polki-cut glass and pearl.",
            "de": "Glockenförmige Kronleuchter-Ohrringe in Polki-Schliff-Glas und Perlen.",
            "fr": "Boucles d'oreilles chandeliers en forme de cloche en verre polki et perle.",
            "es": "Pendientes tipo candelabro en forma de campana con vidrio polki y perlas.",
            "it": "Orecchini chandelier a forma di campana in vetro polki e perle.",
        },
        "long_description": {
            "en": "The traditional Rajasthani jhumka reimagined — polki-cut mirror-glass petals with fresh-water pearl fringes. Lightweight brass core, gold-plated finish.",
            "de": "Der traditionelle Rajasthani-Jhumka neu interpretiert — Polki-Spiegelglasblätter mit Süßwasserperlen-Fransen.",
            "fr": "Le jhumka traditionnel du Rajasthan réinventé — pétales en verre miroir polki avec franges de perles d'eau douce.",
            "es": "El tradicional jhumka de Rajasthan reinventado — pétalos de vidrio espejo polki con flecos de perlas.",
            "it": "Il tradizionale jhumka del Rajasthan reinventato — petali in vetro specchio polki con frange di perle.",
        },
        "image_prompt": "Editorial luxury jewelry photography of Indian bell-shaped jhumka chandelier earrings with polki cut mirror glass petals and fresh water pearl fringes, gold plated, displayed against deep charcoal velvet background, dramatic warm side lighting, macro sharp detail, magazine cover quality Vogue jewelry shoot, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1631161846286-79c1acd4b8f5?w=1200&q=80",
    },
    {
        "slug": "meenakari-bangles-set",
        "name": {
            "en": "Meenakari Enamel Bangles — Set of 4",
            "de": "Meenakari Emaille-Armreifen — 4er-Set",
            "fr": "Bracelets Meenakari Émaillés — Lot de 4",
            "es": "Brazaletes Meenakari Esmaltados — Set de 4",
            "it": "Bracciali Meenakari Smaltati — Set da 4",
        },
        "vertical": "artificial-jewelry",
        "category": "bangles",
        "price_eur": 56.00,
        "unit": "Set of 4 · 2.6 inch",
        "short_description": {
            "en": "Hand-enameled bangles in peacock blue and emerald green — a Rajasthani craft in 60 hours per piece.",
            "de": "Handemaillierte Armreifen in Pfauenblau und Smaragdgrün — 60 Stunden Rajasthan-Handwerk pro Stück.",
            "fr": "Bracelets émaillés à la main en bleu paon et vert émeraude — 60 heures d'artisanat rajasthani par pièce.",
            "es": "Brazaletes esmaltados a mano en azul pavo real y verde esmeralda.",
            "it": "Bracciali smaltati a mano in blu pavone e verde smeraldo.",
        },
        "long_description": {
            "en": "Ancient meenakari enamelling technique from Jaipur — kiln-fired glass powder on hand-hammered brass. Each set contains four graduating bangles.",
            "de": "Antike Meenakari-Emailliertechnik aus Jaipur — im Ofen gebranntes Glaspulver auf handgehämmertem Messing.",
            "fr": "Technique ancestrale d'émaillage meenakari de Jaipur — poudre de verre cuite au four sur laiton martelé main.",
            "es": "Antigua técnica de esmaltado meenakari de Jaipur — polvo de vidrio cocido al horno sobre latón martillado.",
            "it": "Antica tecnica di smaltatura meenakari di Jaipur — polvere di vetro cotta in forno su ottone martellato.",
        },
        "image_prompt": "Editorial luxury jewelry photography of a set of four Indian meenakari enamel bangles in peacock blue and emerald green with intricate hand-painted floral patterns and gold accents, stacked artfully on rich burgundy velvet, dramatic warm side lighting, deep shadows, macro sharp detail, magazine cover quality, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&q=80",
        "badge": {"en": "Handcrafted", "de": "Handgefertigt", "fr": "Fait main", "es": "Hecho a mano", "it": "Fatto a mano"},
    },
    {
        "slug": "temple-jhumki-long",
        "name": {
            "en": "South Temple Long Haram",
            "de": "Süd-Tempel Langer Haram",
            "fr": "Long Collier Temple du Sud",
            "es": "Collar Largo Templo del Sur",
            "it": "Lunga Collana Tempio del Sud",
        },
        "vertical": "artificial-jewelry",
        "category": "necklaces",
        "price_eur": 148.00,
        "unit": "Long chain 32 inch",
        "short_description": {
            "en": "Long temple-jewelry haram — antique-gold finish with ruby-red glass and pearls.",
            "de": "Lange Tempel-Schmuck-Haram-Kette — antik-goldene Ausführung mit rubinrotem Glas und Perlen.",
            "fr": "Long collier de bijoux de temple — finition or antique avec verre rouge rubis et perles.",
            "es": "Collar largo estilo templo — acabado dorado antiguo con vidrio rojo rubí y perlas.",
            "it": "Lunga collana in stile tempio — finitura oro anticato con vetro rosso rubino e perle.",
        },
        "long_description": {
            "en": "Cast in antiqued brass by hereditary silversmiths in Kanchipuram. Traditional goddess-motif pendants set with faceted red glass and edged with fresh-water pearls.",
            "de": "In antikisiertem Messing von Silberschmieden in Kanchipuram gegossen. Traditionelle Göttinnenmotiv-Anhänger mit facettiertem rotem Glas.",
            "fr": "Coulé en laiton antiqué par des orfèvres héréditaires de Kanchipuram. Pendentifs traditionnels aux motifs de déesse en verre rouge facetté.",
            "es": "Fundido en latón antiguo por plateros hereditarios de Kanchipuram. Colgantes tradicionales con motivos de diosa en vidrio rojo facetado.",
            "it": "Fuso in ottone anticato da orafi ereditari di Kanchipuram. Pendenti tradizionali con motivi di dea in vetro rosso sfaccettato.",
        },
        "image_prompt": "Editorial luxury jewelry photography of a long South Indian temple jewelry haram necklace with antique gold pendants featuring goddess motifs, ruby red faceted glass stones and fresh water pearls, displayed hanging against a dark textured wall, dramatic warm gallery lighting, macro sharp detail, magazine cover quality Vogue India shoot, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=1200&q=80",
        "badge": {"en": "Limited", "de": "Limitiert", "fr": "Édition limitée", "es": "Edición limitada", "it": "Edizione limitata"},
    },
    {
        "slug": "oxidised-silver-ring-stack",
        "name": {
            "en": "Oxidised Silver Ring Stack",
            "de": "Oxidiertes Silber-Ring-Set",
            "fr": "Set d'Anneaux en Argent Oxydé",
            "es": "Set de Anillos de Plata Oxidada",
            "it": "Set di Anelli in Argento Ossidato",
        },
        "vertical": "artificial-jewelry",
        "category": "rings",
        "price_eur": 34.00,
        "unit": "Set of 3 · adjustable",
        "short_description": {
            "en": "Bohemian stack of three oxidised-silver rings with tribal motifs.",
            "de": "Bohème-Set aus drei oxidierten Silberringen mit Stammesmotiven.",
            "fr": "Set bohème de trois anneaux en argent oxydé aux motifs tribaux.",
            "es": "Conjunto bohemio de tres anillos de plata oxidada con motivos tribales.",
            "it": "Set boho di tre anelli in argento ossidato con motivi tribali.",
        },
        "long_description": {
            "en": "Hand-cast in an oxidised silver-plated finish — a tribal alphabet of moon, sun and lotus motifs. Fully adjustable band for any finger.",
            "de": "Handgegossen in oxidiertem versilbertem Finish — ein Stammes-Alphabet aus Mond-, Sonnen- und Lotusmotiven.",
            "fr": "Coulé main dans une finition argentée oxydée — un alphabet tribal de motifs lune, soleil et lotus.",
            "es": "Fundido a mano en un acabado plateado oxidado — un alfabeto tribal de motivos de luna, sol y loto.",
            "it": "Fuso a mano in una finitura argentata ossidata — un alfabeto tribale di motivi luna, sole e loto.",
        },
        "image_prompt": "Editorial luxury jewelry photography of a stack of three Indian oxidised silver rings with intricate tribal motifs of moon, sun and lotus, dark blackened silver finish with detailed engravings, stacked artfully on rough dark stone, dramatic warm side lighting, macro sharp detail, deep shadows, magazine quality, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&q=80",
    },

    # ---------- CHRISTMAS DECOR (Seasonal) ----------
    {
        "slug": "christmas-beaded-ornament-set",
        "name": {
            "en": "Beaded Glass Ornament Set",
            "de": "Perlen-Glaskugel-Set",
            "fr": "Ensemble de Boules en Verre Perlé",
            "es": "Juego de Bolas de Cristal con Cuentas",
            "it": "Set di Palline in Vetro Perlato",
        },
        "vertical": "christmas-decor",
        "category": "ornaments",
        "price_eur": 34.00,
        "unit": "Set of 6",
        "short_description": {
            "en": "Six hand-beaded glass baubles in antique gold and deep crimson.",
            "de": "Sechs handperlenbestickte Glaskugeln in Antikgold und tiefem Karmesinrot.",
            "fr": "Six boules en verre perlées à la main en or antique et cramoisi profond.",
            "es": "Seis bolas de cristal con cuentas hechas a mano en oro antiguo y carmesí profundo.",
            "it": "Sei palline in vetro perlate a mano in oro antico e cremisi profondo.",
        },
        "long_description": {
            "en": "Mouth-blown glass hand-strung with tiny glass beads and zari thread by Moradabad artisans. Each ornament is boxed in tissue and ready to gift.",
            "de": "Mundgeblasenes Glas, von Handwerkern aus Moradabad mit winzigen Glasperlen und Zari-Faden bestickt.",
            "fr": "Verre soufflé à la bouche, enfilé à la main avec de minuscules perles de verre et du fil zari par des artisans de Moradabad.",
            "es": "Vidrio soplado a mano, ensartado con diminutas cuentas de vidrio e hilo zari por artesanos de Moradabad.",
            "it": "Vetro soffiato a bocca, infilato a mano con minuscole perline di vetro e filo zari da artigiani di Moradabad.",
        },
        "image_prompt": "Editorial luxury product photography of a set of six ornate Indian beaded glass Christmas baubles in antique gold and deep crimson red with intricate zari thread and tiny glass bead work, arranged on dark moody velvet with soft warm holiday bokeh lights in the background, dramatic side lighting, deep shadows, ultra sharp macro detail, magazine cover quality, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1607454816943-ffd59fbe785d?w=1200&q=80",
        "badge": {"en": "Festive", "de": "Festlich", "fr": "Festif", "es": "Festivo", "it": "Festivo"},
    },
    {
        "slug": "christmas-embroidered-stocking",
        "name": {
            "en": "Hand-Embroidered Christmas Stocking",
            "de": "Handbestickter Weihnachtsstrumpf",
            "fr": "Bas de Noël Brodé à la Main",
            "es": "Media de Navidad Bordada a Mano",
            "it": "Calza di Natale Ricamata a Mano",
        },
        "vertical": "christmas-decor",
        "category": "stockings",
        "price_eur": 26.00,
        "unit": "48 cm",
        "short_description": {
            "en": "Velvet stocking with gold-thread reindeer and holly embroidery.",
            "de": "Samtstrumpf mit Rentier- und Stechpalmenstickerei aus Goldfaden.",
            "fr": "Bas en velours avec broderie de renne et de houx en fil d'or.",
            "es": "Media de terciopelo con bordado de reno y acebo en hilo dorado.",
            "it": "Calza in velluto con ricamo di renna e agrifoglio in filo d'oro.",
        },
        "long_description": {
            "en": "Deep-green cotton velvet with dense gold zardozi embroidery and a plush cuff. Lined and loop-hung, made to hang from the mantel for generations.",
            "de": "Dunkelgrüner Baumwollsamt mit dichter goldener Zardozi-Stickerei und plüschiger Manschette.",
            "fr": "Velours de coton vert profond avec broderie zardozi dorée dense et revers en peluche.",
            "es": "Terciopelo de algodón verde profundo con denso bordado zardozi dorado y puño de felpa.",
            "it": "Velluto di cotone verde profondo con fitto ricamo zardozi dorato e polsino in peluche.",
        },
        "image_prompt": "Editorial luxury product photography of a deep green velvet Christmas stocking with intricate gold zardozi thread embroidery of a reindeer and holly, plush cream cuff, hanging from a dark carved wooden mantel beside softly glowing warm holiday lights, moody cinematic lighting, deep shadows, ultra sharp detail, magazine cover quality",
        "image_hint": "https://images.pexels.com/photos/19580830/pexels-photo-19580830.jpeg?w=1200&q=80",
        "badge": {"en": "Handcrafted", "de": "Handgefertigt", "fr": "Fait main", "es": "Hecho a mano", "it": "Fatto a mano"},
    },
    {
        "slug": "christmas-zari-table-runner",
        "name": {
            "en": "Zari Festive Table Runner",
            "de": "Zari-Festtisch-Läufer",
            "fr": "Chemin de Table Festif Zari",
            "es": "Camino de Mesa Festivo Zari",
            "it": "Runner da Tavola Festivo Zari",
        },
        "vertical": "christmas-decor",
        "category": "table-linen",
        "price_eur": 42.00,
        "unit": "180 × 35 cm",
        "short_description": {
            "en": "Ivory silk-blend runner with gold zari pine and star motifs.",
            "de": "Läufer aus Seidenmischung in Elfenbein mit goldenen Zari-Tannen- und Sternmotiven.",
            "fr": "Chemin en soie mélangée ivoire avec motifs de pin et d'étoiles en zari doré.",
            "es": "Camino de mezcla de seda marfil con motivos de pino y estrellas en zari dorado.",
            "it": "Runner in misto seta avorio con motivi di pino e stelle in zari dorato.",
        },
        "long_description": {
            "en": "Hand-woven ivory silk-blend edged with metallic zari brocade, embroidered with pine boughs and eight-point stars. Sets a festive table without shouting.",
            "de": "Handgewebte elfenbeinfarbene Seidenmischung mit metallischer Zari-Brokatkante, bestickt mit Tannenzweigen und achtzackigen Sternen.",
            "fr": "Mélange de soie ivoire tissé à la main, bordé de brocart zari métallique, brodé de branches de pin et d'étoiles à huit branches.",
            "es": "Mezcla de seda marfil tejida a mano, ribeteada con brocado zari metálico, bordada con ramas de pino y estrellas de ocho puntas.",
            "it": "Misto seta avorio tessuto a mano, bordato con broccato zari metallico, ricamato con rami di pino e stelle a otto punte.",
        },
        "image_prompt": "Editorial luxury product photography of an ivory silk-blend Christmas table runner with metallic gold zari brocade edges and embroidered pine boughs and eight-point stars, elegantly draped on a dark carved wooden dining table with tealights and evergreen sprigs, moody warm cinematic lighting, deep shadows, ultra sharp detail, magazine cover quality",
        "image_hint": "https://images.pexels.com/photos/35100832/pexels-photo-35100832.jpeg?w=1200&q=80",
    },
    {
        "slug": "christmas-star-tree-topper",
        "name": {
            "en": "Zardozi Star Tree Topper",
            "de": "Zardozi-Stern-Baumspitze",
            "fr": "Cimier d'Étoile Zardozi",
            "es": "Estrella para Árbol Zardozi",
            "it": "Puntale a Stella Zardozi",
        },
        "vertical": "christmas-decor",
        "category": "tree-toppers",
        "price_eur": 38.00,
        "unit": "22 cm",
        "short_description": {
            "en": "Padded eight-point star in gold zardozi with glass-bead centre.",
            "de": "Gepolsterter achtzackiger Stern in Gold-Zardozi mit Glasperlenmitte.",
            "fr": "Étoile matelassée à huit branches en zardozi doré avec centre en perles de verre.",
            "es": "Estrella acolchada de ocho puntas en zardozi dorado con centro de cuentas de vidrio.",
            "it": "Stella imbottita a otto punte in zardozi dorato con centro in perline di vetro.",
        },
        "long_description": {
            "en": "A hand-padded velvet star embroidered in raised gold zardozi with a faceted glass-bead heart. Sleeve-mounted to crown a tree or hang as a wall star.",
            "de": "Ein handgepolsterter Samtstern, bestickt mit erhabenem Gold-Zardozi und einem facettierten Glasperlenherz.",
            "fr": "Une étoile en velours matelassée à la main, brodée de zardozi doré en relief avec un cœur en perles de verre à facettes.",
            "es": "Una estrella de terciopelo acolchada a mano, bordada en zardozi dorado en relieve con un corazón de cuentas de vidrio facetadas.",
            "it": "Una stella in velluto imbottita a mano, ricamata in zardozi dorato in rilievo con un cuore in perline di vetro sfaccettate.",
        },
        "image_prompt": "Editorial luxury product photography of an ornate eight-point Christmas tree topper star made of padded velvet with raised gold zardozi metallic thread embroidery and a faceted glass-bead centre, glowing warmly against a dark moody background with soft holiday bokeh, dramatic side lighting, deep shadows, ultra sharp macro detail, magazine cover quality, cinematic",
        "image_hint": "https://images.unsplash.com/photo-1699364911352-5306d68359cb?w=1200&q=80",
        "badge": {"en": "Limited", "de": "Limitiert", "fr": "Édition limitée", "es": "Edición limitada", "it": "Edizione limitata"},
    },
]
